# Generated by Django 4.2.8 on 2024-01-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='TagQuestion',
        ),
    ]
