# Generated by Django 4.2.8 on 2024-01-08 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tag_rating_delete_tagquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tag')),
            ],
            options={
                'db_table': 'TagQuestion',
                'managed': True,
            },
        ),
    ]
