# Generated by Django 4.2.8 on 2024-01-09 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_populartags_bestusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestusers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='populartags',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='bestusers',
            table='BestUsers',
        ),
        migrations.AlterModelTable(
            name='populartags',
            table='PopularTags',
        ),
    ]
